services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localhost123
      POSTGRES_DB: gastosresidenciais_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gastosresidenciais_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sail

  api:
    build:
      context: .
      dockerfile: GastosResidenciais/src/GastosResidenciais.Api/Dockerfile
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Connection: Host=postgres;Port=5432;Database=gastosresidenciais_db;Username=postgres;Password=localhost123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sail

  proxy:
    image: nginx:alpine
    ports:
      - "5443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse-proxy/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - sail

  frontend:
    build:
      context: ./front-spa
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-spa/docker:/usr/src/app/docker
      - ./front-spa/public:/usr/src/app/public
      - ./front-spa/src:/usr/src/app/src
      - ./front-spa/vite.config.ts:/usr/src/app/vite.config.ts
      - ./front-spa/.env:/usr/src/app/.env
      - /usr/src/app/node_modules
    networks:
      - sail
    environment:
      VITE_BASE_URL: https://localhost:5443/api
      NODE_ENV: development
    depends_on:
      - api
    image: react-spa

networks:
  sail:
    driver: bridge

volumes:
  db:
    driver: local