//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastosResidenciais.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GastosResidenciais.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria é incompativel com o tipo de transação..
        /// </summary>
        public static string CATEGORIA_INCOMPATIVEL_COM_TIPO {
            get {
                return ResourceManager.GetString("CATEGORIA_INCOMPATIVEL_COM_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada..
        /// </summary>
        public static string CATEGORIA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("CATEGORIA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria é obrigatória..
        /// </summary>
        public static string CATEGORIA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("CATEGORIA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ser maior que 400 caracteres..
        /// </summary>
        public static string DESCRICAO_INVALIDA {
            get {
                return ResourceManager.GetString("DESCRICAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória..
        /// </summary>
        public static string DESCRICAO_OBRIGATORIA {
            get {
                return ResourceManager.GetString("DESCRICAO_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de finalidade não é válido..
        /// </summary>
        public static string FINALIDADE_ENUM_INVALIDO {
            get {
                return ResourceManager.GetString("FINALIDADE_ENUM_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A idade precisa ser um número válido..
        /// </summary>
        public static string IDADE_NAO_PERMITIDA {
            get {
                return ResourceManager.GetString("IDADE_NAO_PERMITIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser maior que 200 caracteres..
        /// </summary>
        public static string NOME_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada..
        /// </summary>
        public static string PESSOA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("PESSOA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pessoa é obrigatória..
        /// </summary>
        public static string PESSOA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("PESSOA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de transação não é válido..
        /// </summary>
        public static string TIPO_TRANSACAO_ENUM_INVALIDO {
            get {
                return ResourceManager.GetString("TIPO_TRANSACAO_ENUM_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não encontrada..
        /// </summary>
        public static string TRANSACAO_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("TRANSACAO_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor deve ser maior que zero..
        /// </summary>
        public static string VALOR_MAIOR_QUE_ZERO {
            get {
                return ResourceManager.GetString("VALOR_MAIOR_QUE_ZERO", resourceCulture);
            }
        }
    }
}
