<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="UseCases\Relatorios\Pdfs\Fonts\Raleway-Black.ttf" />
	  <None Remove="UseCases\Relatorios\Pdfs\Fonts\Raleway-Regular.ttf" />
	  <None Remove="UseCases\Relatorios\Pdfs\Fonts\WorkSans-Black.ttf" />
	  <None Remove="UseCases\Relatorios\Pdfs\Fonts\WorkSans-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="UseCases\Relatorios\Pdfs\Fonts\Raleway-Black.ttf" />
	  <EmbeddedResource Include="UseCases\Relatorios\Pdfs\Fonts\Raleway-Regular.ttf" />
	  <EmbeddedResource Include="UseCases\Relatorios\Pdfs\Fonts\WorkSans-Black.ttf" />
	  <EmbeddedResource Include="UseCases\Relatorios\Pdfs\Fonts\WorkSans-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
		<PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GastosResidenciais.Communication\GastosResidenciais.Communication.csproj" />
		<ProjectReference Include="..\GastosResidenciais.Domain\GastosResidenciais.Domain.csproj" />
		<ProjectReference Include="..\GastosResidenciais.Exception\GastosResidenciais.Exception.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Logo\logo-md.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
